<a href="https://colab.research.google.com/github/SH00-T/GooglecollabTF-practice/blob/main/tensorflow_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

Initialization

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
x = tf.constant([[1,2,3],[3,4,5]])
x = tf.ones((3,3))
x = tf.zeros((2,3))
x = tf.eye(3) #I(eye) for identity matrix
x = tf.random.normal((3,3),mean=0, stddev=1)
x = tf.random.uniform((3,3),minval=0,maxval=2)
x = tf.range(start = 1 , limit = 10 , delta = 2) #Start = starting value,Limit =  end value, delta = step to limit
x = tf.cast(x, dtype = tf.float64) 
# cast used to convert the data type & tf.float = (16,32,64) ,tf.int(8,16,32,64),tf.bool(0,1)
# these are the different types of cast


Mathematical  Operations


In [ ]:
x = tf.constant([1,2,3])
y = tf.constant([9,8,7])
# Addition
z = tf.add(x,y)
# Another way is 
z = x + y
# Subtraction
z = tf.subtract(x,y)
# Another way is 
z = x - y
# Division
z = tf.divide(x,y)
# Another way is 
z = x / y
# Mulitiplication
z = tf.multiply(x,y)
# Another way is
z = x * y
# Sum
# Tensordot (also known as tensor contraction) sums the product of elements from a and b over the indices specified by axes .
z = tf.tensordot(x,y, axes = 1)
# you are squeezing from bottom and top so that two separate rows become one row.
z = tf.reduce_sum(x*y, axis = 0)
# Element wise exponential
z = x ** 2
# Matrix multiplication
x = tf.random.normal((2,3))
y = tf.random.normal((3,4))
z = tf.matmul(x,y)
# Another way is
z = x @ y

Indexing

In [ ]:
x = tf.constant([1,2,3,4,5,6])
# print(x[:])# print all elements
# print(x[1:]) # print all except  the mentioned indexed element
# print(x[1:3]) # print mentioned from index to index others are omitted
# print(x[::2]) # skip every 2 elements
# print(x[::-1]) # print in reverse order
indices = tf.constant([0,3])
# print(x,indices)
x_indices = tf.gather(x,indices)
# print(x_indices)
x = tf.constant(
                [[1,2],
                 [2,3],
                 [4,5]])
# print(x[0,:])#get 1 st index from to all elements in first index
# print(x[0:2,:])#get 1st two , by using : get all elements 


Reshaping

In [ ]:
  x = tf.range(9)
  x = tf.reshape(x,(3,3))
  print(x)
  x = tf.transpose(x, perm=[1,0])# change columns and row or rearrange the order
  x

tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]], dtype=int32)>